name = "saascritic"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./en"

[[redirects]]
from = "https://saascritic.com/*"
to = "https://www.saascritic.com/:splat"
status = 301
force = true
